### ISSUE TITLE
Do not mix `scrbook` and `geometry`

### ISSUE THREAD

**Issue by philipptempel** [iswunistuttgart/isw_smb_diss#10]
Please don't mix packages `scrbook` and `geometry` without respecting the authors' guidelines. There is a huge amount of typesetting issues coming around when simply `\usepackage{geometry}` in a document based on `\documentclass{scrbook}`.
Please refer to chapter 2 of the [koma script guide](http://mirrors.ctan.org/macros/latex/contrib/koma-script/doc/scrguide-en.pdf) which says

> Many LaTeX classes, including the standard classes, present the user with a largely fixed configuration of margins and page layout. In the standard classes, the choice is limited to selecting a font size. There are separate packages, such as geometry (see [Ume10]), which give the user complete control over, but also full responsibility for, setting the type area and margins.
> KOMA-Script takes a somewhat different approach with the typearea package. Users are offered ways to adjust the design and algorithms based on established typographic standards, making it easier for them to make good choices.

Now of course
> If you have concrete specifications for the margins, typearea is not suitable. In this case, you should use the geometry package (see [Ume10]).

However,
> In the worst case, use the geometry package (see [Ume10]), which is not part of KOMA - Script, or change the page layout parameters of L A TEX yourself. You can find the values as determined by typearea in the log file of your document. The usegeometry option, which you can find in part II, can also improve the interactions between typearea and geometry. This should allow modest adjustments. However, make sure that the proportions of the text area match those of the page, taking the binding correction into account.

**Comment by philipptempel** [comment]
Bump because it seems to have perished on the screens.

**Comment by chhinze** [comment]
I agree that this is not 100 % correct, but I would  it for now as it does its job. I did not notice any real problems so far and no current PhD student writing their thesis has complained yet.

 @philipptempel  Feel free to open a merge request with a patch, if you know how to fix this as long as the following requirements are met:
1. Compliance with [PromO Uni Stuttgart, p. 25](https://elib.uni-stuttgart.de/handle/11682/10344)
2. Interaction with the class does not get significantly more complicated for inexperienced LaTeX users

Otherwise I would close it as wontfix

**Comment by philipptempel** [comment]
Beg to differ and open again.

If I'm not mistaken, your class does not conform with the PromO either/already. See https://github.com/iswunistuttgart/isw_smb_diss/blob/master/isw_smb_diss.cls#L53 which calculates the left (resp. right) margin to `lmargin = 2\lenbasemargin = 2\basemargin = 2*0.7cm = 1.4cm`. PromO says 
>  nach allen Seiten ist ein Rand von mindestens 2 cm zu lassen
I guess, a 1.4cm margin is bigger than a 2cm margin?

**Comment by chhinze** [comment]
`\basemargin`is 1 cm and not 0.7 cm, unless the accepted option is used (which is for print in DIN A5). See <https://github.com/iswunistuttgart/isw_smb_diss/blob/master/isw_smb_diss.cls#L16> for its definition. So for the manuscript the margins on left and right are exactly 2 cm, as required by the PromO.

For the final print in A5 you are right: the margins on left and right are scaled down here. This is proportionally to the size change of the paper format to keep the same aspect ratio. 

As stated before, if you feel motivated to fix the (hypothetical) clash between scrbook and geometry, feel free to submit a patch.
