### ISSUE TITLE
Non-Code Issue: How to for non-coders

### ISSUE THREAD

**Issue by wasseranbord** [iswunistuttgart/isw_smb_diss#12]
Hi developers, 
I hope this is the right plattform to ask this. As I last used github some years ago and am not a coder, setting up the repository was a bit difficult at first. 

Would you be interested in me providing a "how to" for other non-coders as well? (So that others can set up the repository?). 
Thank you so much for taking the time to create this repository and keeping it updated!

Best
V

**Comment by chhinze** [comment]
Hey @wasseranbord, 

sure.  Sounds great. I assume that the steps listed in the [readme](https://github.com/iswunistuttgart/isw_smb_diss#anleitung-zum-aufsetzen-meiner-dissertation) are not detailed enough, right? Maybe you could give some hints, where you would expect more guidance and we will add  this. 
For example, we could guide you step by step through your setup in this issue and add the missing info to the readme afterwards. Alternatively, we could schedule a meeting at ISW (Campus Stadtmitte). If you'd prefer that, just write me an e-mail.

**Comment by chhinze** [comment]
Closed as inactive.
