### ISSUE TITLE
Undefined control sequence \maketitle

### ISSUE THREAD

**Issue by wasseranbord** [iswunistuttgart/isw_smb_diss#6]
Hi all, 

thank you for providing this template! When compiling, I get the following error message concerning the \maketitle command & wanted to ask whether others experience it, too:

> ! Undefined control sequence.
> \maketitle ...\\[\baselineskip ] \oralexamination 
>                                                   \end {tabbing} \end {minip...
> l.109 \maketitle
>               
> The control sequence at the end of the top line
> of your error message was never \def'ed. If you have
> misspelled it (e.g., `\hobx'), type `I' and the correct
> spelling (e.g., `I\hbox'). Otherwise just continue,
> and I'll forget about whatever was undefined.

I am relatively unexperienced in LaTe (only wrote my master thesis with it), but as maketitle is a standard command, I was wondering whether something might be going on in the cls provided? Please find attached my logfile.

[diss_Valeria.log](https://github.com/iswunistuttgart/isw_smb_diss/files/8482133/diss_Valeria.log)

Best Valeria

**Comment by philipptempel** [comment]
Hi Valeria,
I'm no developer here, but briefly skimmed through your log file.

In fact, it isn't `\maketitle` that's undefined but `\oralexamination` which is undefined. Have you used `\dateoforalexamination{42. September 2222}` in your main TeX file?

If yes, then @chhinze should have a look at what's the issue. If no, then please try this first and report back.

**Comment by chhinze** [comment]
Hi Valeria, 

this should work now with the most revent version. Please run `git pull` or download the [isw_smb_diss.cls](https://github.com/iswunistuttgart/isw_smb_diss/blob/master/isw_smb_diss.cls) and [isw_smb_gloss.sty](https://github.com/iswunistuttgart/isw_smb_diss/blob/master/isw_smb_gloss.sty) (if needed) again and recompile. Does this solve your problem?
