### ISSUE TITLE
Two-page document and inner/outer margin

### ISSUE THREAD

**Issue by philipptempel** [iswunistuttgart/isw_smb_diss#7]
Usually, when choosing a two-page document, the inner margin is half the outer margin. That is, on the right page, the right margin is e.g., 2cm, and the inner margin is 1cm. That is because you want equal margins on the left, middle, and right when putting two pages side-by-side.
Right now, the document renders with a huge inner margin (2.80cm) and a small outer margin (1.40cm). Of course, this does not take into BCOR (binding correction). Assuming, however, there is no binding (pasting) of the final document, then the final document looks weird and is against all typographical best practices.
Also, it doesn't follow the komas script guidelines to setting up a two-pages document.

My suggestion:
```latex
\geometry{%
    top=2.00cm,%
    bottom=2.00cm,%
    inner=1.25cm,%
    outer=2.50cm,%
    headheight=0.70cm,%
    headsep=0.70cm,%
    footskip=0.70cm,
    head=32pt,%
}
```
(or whatever other dimensions suit the developers).

**Comment by chhinze** [comment]
Let's try to split this up:

1. Two-sided print in A5 currently sets `2\lenbasemargin` (with lenbasemargin:=0.7 cm) for left and right borders. It is correct, that the inner border would be set to `\lenbasemargin` ususally. However, afterwards the BCOR value would be added. For a typical dissertation with ~1.2 cm thickness this would be around 0.6 cm (half of the thickness), which is roughly again `\lenbasemargin`. This is why I decided to abstract away the BCOR concept and just add it to the inner margin, which should work fine for most dissertations. People with more profound knowledge of typesetting can still modify the margins to their needs.
2. The assumption that there is no binding:
    -  is probably mostly true for the electronic version, where one-sided output should be used anyways,
    - the other case would be handing in the manuscript, where probably spiral bindings are used. For the manuscript the university requires a margin of at least 2 cm for all sides ([Richtlinien für die äußere Form der Veröffentlichung von Dissertationen, ](https://elib.uni-stuttgart.de/bitstream/11682/10344/1/Promotionsordnung_%2001.03.2019_mit%20Merkblatt.pdf)). Using an outer margin of 4cm seems a bit excessive.

This is why I would leave it like this for now, unless there are more users supporting this. However, please feel free to adapt the geometry for yourself.
